services:
  app:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://litellm_user:litellm_secure_password_change_this@host.docker.internal:5432/ragdb
    restart: always

volumes:
  postgres_data:
